In [1]:
import pandas as pd
import numpy as np
f = pd.read_csv('pandas_tutorial_read.csv', delimiter=';')
f

      2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
0     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
1     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
2     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
3     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
4     2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
5     2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
6     2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
7     2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
8     2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America
9     2018-01-01 00:07:57  read  country_5  2458151271  AdWords           Asia
10    2018-01-01 00:08:57  read  country_7  2458151272      SEO      Australia
11    2018-01-01 00:09:11  read  country_5  2458151273   Reddit           Asia
12    2018-01-01 00:09:29  read  country_2  2458151274   Reddit         Europe
13    2018-01-01 00:11:06  read  country_7  2458151275   Reddit         Africa
14    2018-01-01 00:11:22  read  country_7  2458151276      SEO  North America
15    2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
16    2018-01-01 00:13:06  read  country_2  2458151278   Reddit           Asia
17    2018-01-01 00:13:39  read  country_4  2458151279      SEO  North America
18    2018-01-01 00:14:53  read  country_2  2458151280   Reddit           Asia
19    2018-01-01 00:15:44  read  country_2  2458151281   Reddit           Asia
20    2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
21    2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
22    2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
23    2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
24    2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America
25    2018-01-01 00:20:18  read  country_5  2458151287      SEO  North America
26    2018-01-01 00:20:44  read  country_2  2458151288      SEO  North America
27    2018-01-01 00:23:16  read  country_2  2458151289   Reddit           Asia
28    2018-01-01 00:23:51  read  country_7  2458151290   Reddit           Asia
29    2018-01-01 00:24:52  read  country_6  2458151291      SEO  North America
...                   ...   ...        ...         ...      ...            ...
1764  2018-01-01 23:41:11  read  country_2  2458153026   Reddit         Africa
1765  2018-01-01 23:41:51  read  country_5  2458153027  AdWords           Asia
1766  2018-01-01 23:43:54  read  country_5  2458153028  AdWords         Europe
1767  2018-01-01 23:44:52  read  country_8  2458153029   Reddit  South America
1768  2018-01-01 23:45:09  read  country_5  2458153030  AdWords      Australia
1769  2018-01-01 23:45:12  read  country_6  2458153031   Reddit           Asia
1770  2018-01-01 23:45:56  read  country_5  2458153032  AdWords         Africa
1771  2018-01-01 23:45:58  read  country_7  2458153033      SEO  South America
1772  2018-01-01 23:46:13  read  country_8  2458153034   Reddit           Asia
1773  2018-01-01 23:46:22  read  country_2  2458153035  AdWords           Asia
1774  2018-01-01 23:47:19  read  country_2  2458153036  AdWords           Asia
1775  2018-01-01 23:49:04  read  country_6  2458153037   Reddit           Asia
1776  2018-01-01 23:49:52  read  country_5  2458153038      SEO  North America
1777  2018-01-01 23:51:17  read  country_2  2458153039   Reddit           Asia
1778  2018-01-01 23:51:25  read  country_4  2458153040      SEO  South America
1779  2018-01-01 23:51:46  read  country_8  2458153041  AdWords         Africa
1780  2018-01-01 23:51:52  read  country_2  2458153042   Reddit           Asia
1781  2018-01-01 23:53:03  read  country_2  2458153043  AdWords           Asia
1782  2018-01-01 23:53:33  read  country_3  2458153044   Reddit           Asia
1783  2018-01-01 23:54:03  read  country_2  2458153045      SEO  North America
1784  2018-01-01 23:54:26  read  country_2  2458153046  AdWords         Africa
1785  2018-01-01 23:54:39  read  country_6  2458153047   Reddit           Asia
1786  2018-01-01 23:54:45  read  country_2  2458153048   Reddit           Asia
1787  2018-01-01 23:55:04  read  country_7  2458153049  AdWords         Europe
1788  2018-01-01 23:56:42  read  country_4  2458153050  AdWords           Asia
1789  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1790  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1791  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1792  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1793  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

[1794 rows x 6 columns]

In [8]:
p = f.iloc[20:25,:]
p

    2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
20  2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
21  2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
22  2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
23  2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
24  2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America

In [9]:
p[p.SEO == "Reddit"]

    2018-01-01 00:01:01  read  country_7  2458151261     SEO North America
20  2018-01-01 00:15:50  read  country_7  2458151282  Reddit        Africa
22  2018-01-01 00:17:31  read  country_2  2458151284  Reddit          Asia
23  2018-01-01 00:17:58  read  country_7  2458151285  Reddit        Africa

In [10]:
p[p<2458151285]

    2018-01-01 00:01:01  read  country_7    2458151261      SEO  North America
20  2018-01-01 00:15:50  read  country_7  2.458151e+09   Reddit         Africa
21  2018-01-01 00:17:15  read  country_2  2.458151e+09  AdWords         Europe
22  2018-01-01 00:17:31  read  country_2  2.458151e+09   Reddit           Asia
23  2018-01-01 00:17:58  read  country_7           NaN   Reddit         Africa
24  2018-01-01 00:18:55  read  country_2           NaN  AdWords  North America